spring.application.name=springboot

server.port = 8080
spring.datasource.url=jdbc:oracle:thin:@192.168.0.43:1521/XE
spring.datasource.username=fourjo
spring.datasource.password=4444
spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver
mybatis.configuration.map-underscore-to-camel-case=true
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp