create table INTEGRATED_ACCOUNT
(
    LOGIN_ID        VARCHAR2(50),
    PASSWORD        VARCHAR2(200),
    USER_TYPE       VARCHAR2(10),
    LAST_LOGIN_DATE DATE,
    JOIN_DATE       DATE,
    ACCOUNT_ID      NUMBER
);
create sequence SEQ_INTEGRATED_ACCOUNT
    START WITH 1
    increment by 1
    MAXVALUE 999999
    MINVALUE 1
    CYCLE
    NOCACHE;
INSERT INTO INTEGRATED_ACCOUNT VALUES ('testG', '1111', 'G',
                                       SYSDATE, SYSDATE, SEQ_INTEGRATED_ACCOUNT.NEXTVAL);
INSERT INTO INTEGRATED_ACCOUNT VALUES ('testD', '2222', 'D',
                                       SYSDATE, SYSDATE, SEQ_INTEGRATED_ACCOUNT.NEXTVAL);
commit;
SELECT * FROM INTEGRATED_ACCOUNT;

-- SELECT COUNT(*) FROM INTEGRATED_ACCOUNT
-- WHERE USER_TYPE = #{USER_TYPE} AND LOGIN_ID = #{ID} AND PASSWORD = #{PWD}
